In [4]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import string # special operations on strings
import spacy # language models

from matplotlib.pyplot import imread
from matplotlib import pyplot as plt
from wordcloud import WordCloud
%matplotlib inline

In [5]:
!python -m spacy download en_core_web_md

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/conda/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpo

In [38]:
import pandas
tweets=pd.read_csv("../input/datatweet/Tweets.txt",error_bad_lines=False, sep=';')

In [39]:
tweets

X
0   234 tweets with "loser"  I feel sorry for Rosi...
1   tweets with "dumb" or "dummy" You must admit t...
2   204 tweets with "terrible" I loved beating the...
3   183 tweets with "stupid" @michellemalkin You w...
4                                                   .
5   156 tweets with "weak" There is no longer a Be...
6                                                   .
7    117 tweets with "dope" or "dopey" Dopey  @Lor...
8                                                   .
9   115 tweets with "dishonest" A dishonest slob o...
10  101 tweets with "lightweight" I can't resist h...
11  92 tweets with "incompetent" or "incompetence"...
12  91 tweets with "boring" The Emmys are sooooo b...
13  83 tweets with "fool" Dopey Sugar @Lord_Sugar—...
14  72 tweets with "pathetic" Sleep eyes @ChuckTod...
15  64 tweets with variations of "haters and loser...
16  52 tweets with "moron" If the morons who kille...
17  50 tweets with "racist" In that @TimeWarner ha...
18  45 tweets with "clown" .@FrankLuntz, your so-c...
19  39 tweets with "overrated" or "over-rated" "@s...
20  37 tweets with "disgusting" Barney Frank looke...
21   28 tweets with "goofy" When Mitt Romney asked...
22  25 tweets with "low rating" or "bad rating" Ju...
23  18 tweets with "no talent" Isn't it crazy that...
24  15 tweets with "lowlife", "low-life", or "low ...
25  106 tweets implying "global warming" is fake T...
26  84 tweets implying Obama is foreign (birtheris...
27  31 tweets implying "autism" is caused by vacci...
28  586 tweets with "poll" Even though every poll,...
29  421 tweets with "money" .@Lord_Sugar If you di...
30  343 tweets with "ratings" or "rated" @Toure If...
31  Retaliation It makes me feel so good to hit "s...
32  Isn't it crazy, I'm worth billions of dollars,...
33   Isn't it crazy that people of little or no ta...
34  Whenever I tweet, some call it a tirade..total...
35  I was viciously attacked by Mr. Khan at the De...
36   I study cowards and stupid people "@MrMarin88...
37   Ft Lauderdale plaintiffs must pay me close to...

In [40]:
tweets = [X.strip() for X in tweets.X] # remove both the leading and the trailing characters
tweets = [X for X in tweets if X] # removes empty strings, because they are considered in Python as False
tweets[0:10]

['234 tweets with "loser"  I feel sorry for Rosie \'s new partner in love whose parents are devastated at the thought of their daughter being with @Rosie--a true loser. — Donald J. Trump (@realDonaldTrump) December 14, 2011 222.',
 'tweets with "dumb" or "dummy" You must admit that Bryant Gumbel is one of the dumbest racists around - an arrogant dope with no talent. Failed at CBS etc-why still on TV? — Donald J. Trump (@realDonaldTrump) August 21, 2013 .',
 '204 tweets with "terrible" I loved beating these two terrible human beings. I would never recommend that anyone use her lawyer, he is a total loser! — Donald J. Trump (@realDonaldTrump) May 23, 2013 .',
 '183 tweets with "stupid" @michellemalkin You were born stupid! — Donald J. Trump (@realDonaldTrump) March 22, 2013',
 '.',
 '156 tweets with "weak" There is no longer a Bernie Sanders "political revolution." He is turning out to be a weak and somewhat pathetic figure,wants it all to end! — Donald J. Trump (@realDonaldTrump) July 2

In [41]:
# Joining the list into one string/text
text = ' '.join(tweets)
text

'234 tweets with "loser"  I feel sorry for Rosie \'s new partner in love whose parents are devastated at the thought of their daughter being with @Rosie--a true loser. — Donald J. Trump (@realDonaldTrump) December 14, 2011 222. tweets with "dumb" or "dummy" You must admit that Bryant Gumbel is one of the dumbest racists around - an arrogant dope with no talent. Failed at CBS etc-why still on TV? — Donald J. Trump (@realDonaldTrump) August 21, 2013 . 204 tweets with "terrible" I loved beating these two terrible human beings. I would never recommend that anyone use her lawyer, he is a total loser! — Donald J. Trump (@realDonaldTrump) May 23, 2013 . 183 tweets with "stupid" @michellemalkin You were born stupid! — Donald J. Trump (@realDonaldTrump) March 22, 2013 . 156 tweets with "weak" There is no longer a Bernie Sanders "political revolution." He is turning out to be a weak and somewhat pathetic figure,wants it all to end! — Donald J. Trump (@realDonaldTrump) July 24, 2016 . 117 tweets 

In [42]:
#Punctuation
no_punc_text = text.translate(str.maketrans('', '', string.punctuation)) #with arguments (x, y, z) where 'x' and 'y'
# must be equal-length strings and characters in 'x'
# are replaced by characters in 'y'. 'z'
# is a string (string.punctuation here)
no_punc_text

'234 tweets with loser  I feel sorry for Rosie s new partner in love whose parents are devastated at the thought of their daughter being with Rosiea true loser — Donald J Trump realDonaldTrump December 14 2011 222 tweets with dumb or dummy You must admit that Bryant Gumbel is one of the dumbest racists around  an arrogant dope with no talent Failed at CBS etcwhy still on TV — Donald J Trump realDonaldTrump August 21 2013  204 tweets with terrible I loved beating these two terrible human beings I would never recommend that anyone use her lawyer he is a total loser — Donald J Trump realDonaldTrump May 23 2013  183 tweets with stupid michellemalkin You were born stupid — Donald J Trump realDonaldTrump March 22 2013  156 tweets with weak There is no longer a Bernie Sanders political revolution He is turning out to be a weak and somewhat pathetic figurewants it all to end — Donald J Trump realDonaldTrump July 24 2016  117 tweets with dope or dopey Dopey  LordSugar Im worth 8 billion and you

In [43]:
#Tokenization
from nltk.tokenize import word_tokenize
text_tokens = word_tokenize(no_punc_text)
print(text_tokens[0:50])

['234', 'tweets', 'with', 'loser', 'I', 'feel', 'sorry', 'for', 'Rosie', 's', 'new', 'partner', 'in', 'love', 'whose', 'parents', 'are', 'devastated', 'at', 'the', 'thought', 'of', 'their', 'daughter', 'being', 'with', 'Rosiea', 'true', 'loser', '—', 'Donald', 'J', 'Trump', 'realDonaldTrump', 'December', '14', '2011', '222', 'tweets', 'with', 'dumb', 'or', 'dummy', 'You', 'must', 'admit', 'that', 'Bryant', 'Gumbel', 'is']


In [44]:
len(text_tokens)

1282

In [45]:
#Remove stopwords
import nltk
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')

my_stop_words = stopwords.words('english')
my_stop_words.append('the')
no_stop_tokens = [word for word in text_tokens if not word in my_stop_words]
print(no_stop_tokens[0:40])

[nltk_data] Error loading punkt: <urlopen error [Errno -3] Temporary
[nltk_data]     failure in name resolution>
[nltk_data] Error loading stopwords: <urlopen error [Errno -3]
[nltk_data]     Temporary failure in name resolution>
['234', 'tweets', 'loser', 'I', 'feel', 'sorry', 'Rosie', 'new', 'partner', 'love', 'whose', 'parents', 'devastated', 'thought', 'daughter', 'Rosiea', 'true', 'loser', '—', 'Donald', 'J', 'Trump', 'realDonaldTrump', 'December', '14', '2011', '222', 'tweets', 'dumb', 'dummy', 'You', 'must', 'admit', 'Bryant', 'Gumbel', 'one', 'dumbest', 'racists', 'around', 'arrogant']


In [46]:
#Noramalize the data
lower_words = [x.lower() for x in no_stop_tokens]
print(lower_words[0:25])

['234', 'tweets', 'loser', 'i', 'feel', 'sorry', 'rosie', 'new', 'partner', 'love', 'whose', 'parents', 'devastated', 'thought', 'daughter', 'rosiea', 'true', 'loser', '—', 'donald', 'j', 'trump', 'realdonaldtrump', 'december', '14']


In [47]:
#Stemming
from nltk.stem import PorterStemmer
ps = PorterStemmer()
stemmed_tokens = [ps.stem(word) for word in lower_words]
print(stemmed_tokens[0:40])

['234', 'tweet', 'loser', 'i', 'feel', 'sorri', 'rosi', 'new', 'partner', 'love', 'whose', 'parent', 'devast', 'thought', 'daughter', 'rosiea', 'true', 'loser', '—', 'donald', 'j', 'trump', 'realdonaldtrump', 'decemb', '14', '2011', '222', 'tweet', 'dumb', 'dummi', 'you', 'must', 'admit', 'bryant', 'gumbel', 'one', 'dumbest', 'racist', 'around', 'arrog']


In [48]:
# NLP english language model of spacy library
nlp = spacy.load('en') 

In [49]:
# lemmas being one of them, but mostly POS, which will follow later
doc = nlp(' '.join(no_stop_tokens))
print(doc[0:40])

234 tweets loser I feel sorry Rosie new partner love whose parents devastated thought daughter Rosiea true loser — Donald J Trump realDonaldTrump December 14 2011 222 tweets dumb dummy You must admit Bryant Gumbel one dumbest racists around arrogant


In [50]:
lemmas = [token.lemma_ for token in doc]
print(lemmas[0:25])

['234', 'tweet', 'loser', '-PRON-', 'feel', 'sorry', 'Rosie', 'new', 'partner', 'love', 'whose', 'parent', 'devastate', 'think', 'daughter', 'Rosiea', 'true', 'loser', '—', 'Donald', 'J', 'Trump', 'realDonaldTrump', 'December', '14']


# Feature Extraction

In [51]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(lemmas)

In [52]:
print(vectorizer.vocabulary_)

{'234': 24, 'tweet': 394, 'loser': 241, 'pron': 307, 'feel': 160, 'sorry': 353, 'rosie': 327, 'new': 272, 'partner': 289, 'love': 243, 'whose': 423, 'parent': 288, 'devastate': 127, 'think': 377, 'daughter': 123, 'rosiea': 328, 'true': 389, 'donald': 134, 'trump': 390, 'realdonaldtrump': 315, 'december': 125, '14': 7, '2011': 13, '222': 22, 'dumb': 138, 'dummy': 140, 'must': 267, 'admit': 47, 'bryant': 91, 'gumbel': 184, 'one': 283, 'dumbest': 139, 'racist': 311, 'around': 58, 'arrogant': 59, 'dope': 135, 'talent': 368, 'fail': 154, 'cbs': 98, 'etcwhy': 149, 'still': 357, 'tv': 393, 'august': 63, '21': 20, '2013': 15, '204': 19, 'terrible': 373, 'beat': 75, 'two': 396, 'human': 196, 'being': 77, 'would': 430, 'never': 271, 'recommend': 317, 'anyone': 57, 'use': 400, 'lawyer': 231, 'total': 385, 'may': 252, '23': 23, '183': 11, 'stupid': 361, 'michellemalkin': 258, 'bear': 74, 'march': 250, '22': 21, '156': 9, 'weak': 414, 'there': 375, 'long': 238, 'bernie': 78, 'sanders': 329, 'politi

In [53]:
print(vectorizer.get_feature_names()[50:100])
print(X.toarray()[50:100])

['ago', 'allow', 'already', 'always', 'amazing', 'an', 'anger', 'anyone', 'around', 'arrogant', 'ask', 'assholetotal', 'attack', 'august', 'autism', 'awkward', 'back', 'backexcept', 'bad', 'bankruptcynow', 'barackobamas', 'barney', 'basic', 'be', 'bear', 'beat', 'become', 'being', 'bernie', 'biased', 'big', 'billion', 'birth', 'birtherism', 'bldgs', 'blogger', 'blue', 'bore', 'boring', 'breakdown', 'brutal', 'bryant', 'business', 'call', 'calm', 'can', 'care', 'cause', 'cbs', 'certificate']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [54]:
print(X.toarray().shape)

(923, 433)


# Let's see how can bigrams and trigrams can be included here

In [55]:
vectorizer_ngram_range = CountVectorizer(analyzer='word',ngram_range=(1,3),max_features = 100)
bow_matrix_ngram =vectorizer_ngram_range.fit_transform(tweets)

In [56]:
print(vectorizer_ngram_range.get_feature_names())
print(bow_matrix_ngram.toarray())

['10', '2012', '2013', '2016', 'about', 'all', 'always', 'am', 'an', 'and', 'are', 'at', 'august', 'back', 'bad', 'be', 'billion', 'boring', 'bryant', 'but', 'by', 'can', 'crazy', 'december', 'dishonest', 'don', 'donald', 'donald trump', 'donald trump realdonaldtrump', 'dopey', 'dumb', 'feel', 'for', 'get', 'has', 'have', 'he', 'if', 'in', 'is', 'isn', 'it', 'just', 'know', 'life', 'loser', 'low', 'may', 'me', 'moron', 'my', 'never', 'no', 'no talent', 'not', 'of', 'of the', 'on', 'or', 'pathetic', 'people', 'realdonaldtrump', 'realdonaldtrump august', 'realdonaldtrump december', 'realdonaldtrump may', 'say', 'so', 'stupid', 'talent', 'that', 'that people', 'the', 'those', 'time', 'to', 'total', 'trump', 'trump realdonaldtrump', 'trump realdonaldtrump august', 'trump realdonaldtrump december', 'trump realdonaldtrump february', 'trump realdonaldtrump july', 'trump realdonaldtrump may', 'trump realdonaldtrump september', 'tweets', 'tweets implying', 'tweets with', 'very', 'was', 'what', 

# TFidf vectorizer

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer_n_gram_max_features = TfidfVectorizer(norm="l2",analyzer='word', ngram_range=(1,3), max_features = 500)
tf_idf_matrix_n_gram_max_features =vectorizer_n_gram_max_features.fit_transform(tweets)
print(vectorizer_n_gram_max_features.get_feature_names())
print(tf_idf_matrix_n_gram_max_features.toarray())

['10', '10 2012', '12', '14', '15', '18', '18 2013', '18 tweets', '18 tweets with', '183', '183 tweets', '183 tweets with', '19', '19 2016', '2011', '2011 222', '2012', '2013', '2014', '2015', '2016', '204', '21', '23', '23 2013', '24', '24 2016', '92 tweets', 'about', 'about me', 'accomplishments', 'accomplishments are', 'accomplishments are great', 'again', 'all', 'always', 'am', 'an', 'and', 'and you', 'are', 'are great', 'are great with', 'around', 'at', 'at the', 'august', 'autism', 'back', 'bad', 'bad things', 'bad things about', 'be', 'be so', 'be so critical', 'been', 'billion', 'boring', 'bryant', 'bryant gumbel', 'but', 'by', 'called', 'can', 'can be', 'can be so', 'cbs', 'clown', 'come', 'crazy', 'crazy that', 'crazy that people', 'critical', 'critical of', 'critical of those', 'december', 'december 10', 'december 10 2012', 'disgusting', 'dishonest', 'don', 'donald', 'donald trump', 'donald trump realdonaldtrump', 'dope', 'dopey', 'dumb', 'dumb racist', 'dummy', 'employ', 'e

#  Generate wordcloud

In [58]:
# Import packages
import matplotlib.pyplot as plt
%matplotlib inline
from wordcloud import WordCloud, STOPWORDS
# Define a function to plot word cloud
def plot_cloud(wordcloud):
    # Set figure size
    plt.figure(figsize=(40, 30))
    # Display image
    plt.imshow(wordcloud) 
    # No axis details
    plt.axis("off");

In [ ]:
# Generate wordcloud
stopwords = STOPWORDS
stopwords.add('will')
wordcloud = WordCloud(width = 3000, height = 2000, background_color='black', max_words=100,colormap='Set2',stopwords=stopwords).generate(text)
# Plot
plot_cloud(wordcloud)